Feature/110 Add content local task for alert banners
localgovdrupal/localgov_alert_banner pull request #111
Opened 2021-02-02 02:51 UTC by tebb

I have added the 'Alert banners' local task and tested that it appears after routing and links cache is flushed.

I added a second commit which (I believe) corrects some capitalisation and a typo.  I wasn't sure if it's OK to do that in this specific issue.

2021-03-17 23:09 UTC, andybroomfield commented
@tebb is this reviewable?

2021-03-18 21:32 UTC, tebb commented
Thanks @andybroomfield - Yes please.

(We thought that creating pull requests automatically queued things for review.  Should we be requesting code reviews?)

2021-03-23 09:15 UTC, andybroomfield requested changes
I've installed this and it worked fine at first, however the tabs are missing when a user goes to the manage alert banners page.
Will post screenshots shortly.

2021-03-29 08:11 UTC, andybroomfield requested changes
Thanks for your work @tebb and apologies for late reviewing.
I had a look and overall good, however there are some quirks I spotted with the tabs not showing once I go to the manage alert banner page. See inline comments.

2021-03-29 08:11 UTC, andybroomfield commented on localgov_alert_banner.links.task.yml
> +  route_name: view.localgov_admin_manage_alert_banners.localgov_alert_banner_admin_list
Can we change the route name to `entity.localgov_alert_banner.collection`
Theres a weird bug that when you go to the alert banner page the tabs no longer show. I think its to do with defining a collection route in the entity class, but we don't use the collection, we use the view. This causes issues with the menu / tab display but we will sort these out in another issue.

2021-03-29 08:11 UTC, andybroomfield commented on localgov_alert_banner.links.task.yml
> +  base_route:  system.admin_content
Remove the extra space
`base_route: system.admin_content`

2021-03-29 08:11 UTC, andybroomfield commented on localgov_alert_banner.links.task.yml
> +  title: 'Alert banners'
We need to add `weight: 50` to the bottom so it shows last in list.

2021-04-14 13:03 UTC, andybroomfield commented
I've added the fixes, if theres anyone who can give this a review before I merge.
Then I can get a release prepped.

2021-04-14 15:46 UTC, danchamp approved these changes
Looks good, tested and working as expected.

2021-04-14 15:54 UTC, andybroomfield commented
Thanks @danchamp

2021-04-14 15:54 UTC, merged