Set the title colour for notable person messages
localgovdrupal/localgov_alert_banner pull request #225
Opened 2022-10-24 07:30 UTC by opdavies

When using the "Death of a notable person" alert type which sets a black background colour, the title - which is also set to black - isn't visible.

This PR sets an explicit text colour for the title within that alert type - ensuring that it can be seen and read.

I did consider opening this PR against the `localgov_base` theme but thought that it made more sense to do so within the alert banner module, although I'd be happy to re-submit it if needed.

## UI changes

Before:

![Screenshot 2022-10-24 at 01-12-20 Welcome! test](https://user-images.githubusercontent.com/339813/197471121-f6fb447f-be45-40fb-a419-740cb79b8c0c.png)

After:

![Screenshot 2022-10-24 at 01-18-37 Welcome! test](https://user-images.githubusercontent.com/339813/197471145-195f0f0f-426c-4f5b-9ca9-98ccde732667.png)

2022-10-24 12:46 UTC, finnlewis commented
Hey @opdavies, thanks for this. 

Looks good to me, but hopefully @andybroomfield can take a look and we can merge and release at our "Merge Monday" call today.

2022-10-24 13:21 UTC, finnlewis commented
@markconroy @msayoung how's this look for you?

2022-10-24 13:25 UTC, finnlewis approved these changes
Discussing at Merge Monday, looks good to @markconroy and happy to merge it. 

Might just hang on to check with @andybroomfield as the lead maintainer.

2022-10-24 14:23 UTC, andybroomfield commented
Thanks @opdavies 
I belive this change is best made in localgov_base, as that is where the title colour is being set.
(The h2 colour sets it).
Although looking on a default install, even base Olivero theme is overriding the h2 colours.
I suppose its how we feel about having it here, as it will then need to be overridden for all theme builders.

Maybe 
````css
.localgov-alert-banner .localgov-alert-banner__title {
  color: inherit;
}
````
Instead?
Would we need to apply it to the other banners and fields also?

2022-10-24 14:35 UTC, markconroy commented
Here's a PR for the `localgov_base` theme.

2022-10-24 15:45 UTC, andybroomfield requested changes, later dismissed
Thanks for the fix @opdavies.
See my comment which I think would be the way to fix this.

2022-10-24 15:45 UTC, andybroomfield commented on css/localgov-alert-banner.css
> +}
I don't think we should have the `|` there.
Lets change this to 
````css
.localgov-alert-banner .localgov-alert-banner__title {
  color: inherit;
}
````
This is so it applies a fix to all banners, and that they use the colour assigned to it via `.localgov-alert-banner`. and can then be overridden in themes by just appling a color to that class.

2022-10-27 15:14 UTC, finnlewis commented
@opdavies any thoughts on the above?

2022-11-07 13:59 UTC, andybroomfield commented
Looks like I can push directly so maybe we can look at this on merge monday.

2022-11-07 14:04 UTC, andybroomfield commented
Do we need the Github test update for javascript tests?

2022-11-07 14:24 UTC, finnlewis approved these changes
Yay! Thanks @andybroomfield

2022-11-07 14:24 UTC, merged